# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"square": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://Drew.github.io/playing_with_nbdev/"

git_url = "https://github.com/Drew/playing_with_nbdev/tree/master/"

def custom_doc_links(name): return None
